### ISSUE TITLE
Macbook M1 Compatibility with quantaq-cli 0.30

### ISSUE THREAD

**Issue by fredmurolo** [quant-aq/cli#19]
When running Python 3.8.11 in a conda env, quantaq-cli 0.30 cannot be installed as wheel can't be built for pyarrow 0.70. Running pip install directly from Python terminal on Macbook with M1 ran into problems with NumPy on Python 3.10.4. This appears to be a universal issue with M1 Macbook's and older revisions of dependencies.

**Comment by dhhagan** [comment]
Hey @fredmurolo when you get a chance, can you try installing [v0.4.0a0](https://pypi.org/manage/project/quantaq-cli/release/0.4.0a0/)?

**Comment by dhhagan** [comment]
Hey @fredmurolo can you confirm whether or not this was fixed? I finally was able to get a couple of M1 macs but they haven't shipped yet.
